### ISSUE TITLE
(Mc 1.19.2) Downloaded 1.19.2 version, says it needs 1.19.2 version

### ISSUE THREAD

**Issue by Stratdan** [AnOpenSauceDev/Methane-mod#10]
![image](https://user-images.githubusercontent.com/85818065/211877546-a08e0c32-c30a-4c5f-ada9-6bfd26ed54bf.png)

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Methane' (methane) 1.4 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'Methane' (methane) 1.4 requires any version before 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![image](https://user-images.githubusercontent.com/85818065/211877197-db99fedb-cf0b-4a12-9e60-1b69b49fa9a1.png)

What??

**Comment by AnOpenSauceDev** [comment]
@Stratdan should be fixed in https://github.com/AnOpenSauceDev/Methane-mod/commit/9116db47e3a2c4a4caf3098ad5f5ce9000ff6856

**Comment by AnOpenSauceDev** [comment]
@Stratdan [the fixed backport](https://modrinth.com/mod/methane/version/1.4.5-backport-2)
