### ISSUE TITLE
Question about Lunar Client Support

### ISSUE THREAD

**Issue by kispintyi** [AnOpenSauceDev/Methane-mod#100]
## 💡 The Idea.
Will you support Lunar Client sometime?

## 🤔 How should it be accomplished?
Methane compatible with Lunar Client

## 📝 Anything else.
-

**Comment by AnOpenSauceDev** [comment]
Not sure what you mean by that, I'm pretty sure Lunar Client just kind of... takes open-source mods as they please? I'm pretty sure if you want Lunar Client to have Methane, you can go ask them to include it.

**Comment by kispintyi** [comment]
They introduced custom mods support (anyone can add any mod but there a few like yours which is broken on the client)

**Comment by kispintyi** [comment]
[crash-2024-05-31_20.34.36-client.txt](https://github.com/user-attachments/files/15517542/crash-2024-05-31_20.34.36-client.txt)

**Comment by AnOpenSauceDev** [comment]
Aaand Lunar Client has taken the same patch that I've used.

And they used the same priority as me, making Methane crash lunar.

**Comment by kispintyi** [comment]
Oh, so what does this mean then? I'm not that technical

**Comment by AnOpenSauceDev** [comment]
Lunar client messes with the same function i use for particle "optimization" that I use (whether or not it does the same thing I do not know), at the same priority and breaks the game because of that.

**Comment by kispintyi** [comment]
Oh, and if I had to guess you can fix it by checking if the player uses Lunar right?
Any ETA?

**Comment by AnOpenSauceDev** [comment]
I could via a mixin plugin (throwing away the whole optimization), but messing with the priority and quickly uploading a new build might fix it all.

**Comment by AnOpenSauceDev** [comment]
try seeing if [the new build works](https://github.com/AnOpenSauceDev/Methane-mod/actions/runs/9329731638)

**Comment by kispintyi** [comment]
It crashed: 
[crash-2024-06-01_13.04.58-client.txt](https://github.com/user-attachments/files/15521406/crash-2024-06-01_13.04.58-client.txt)

**Comment by AnOpenSauceDev** [comment]
Just remembered that Lunar Client's new "patch" is called `lunar$disableCollisionChecks`, so it's probably directly breaking Methane. (Also, Lunar really shouldn't be using this awful hack, it totally breaks vanilla particle behaviour)

**Comment by kispintyi** [comment]
:/ so it can only be solved by Lunar?

**Comment by AnOpenSauceDev** [comment]
Not quite, [try this build](https://github.com/AnOpenSauceDev/Methane-mod/actions/runs/9329932258), that throws an error and disables the particle optimization before lunar can break it.

**Comment by kispintyi** [comment]
It works! 😁

**Comment by kispintyi** [comment]
Btw It's always on fullbright for some reason no matter what I do
![image](https://github.com/AnOpenSauceDev/Methane-mod/assets/116653691/ffc7e798-6529-4edb-9332-ba3065d3d115)

**Comment by kispintyi** [comment]
![image](https://github.com/AnOpenSauceDev/Methane-mod/assets/116653691/0616fab3-80d7-4fed-83b5-f0e249b767e9)
### Legacy Lighting Engine Disabled

**Comment by AnOpenSauceDev** [comment]
you have to set the actual keybind to toggle it, the legacy lighting engine is just the way the fullbright is achieved (legacy engine disabled is typically much faster).

**Comment by kispintyi** [comment]
Inventory is weird (doesn't render correctly):
![image](https://github.com/AnOpenSauceDev/Methane-mod/assets/116653691/9455e9a6-b070-40a3-9cf7-b3f2877848dc)

**Comment by kispintyi** [comment]
Oh okay

**Comment by AnOpenSauceDev** [comment]
that's because you have the destructive optimization enabled that removes background (because they're slow, and I had a case where I need a bit more performance).

**Comment by kispintyi** [comment]
Yeah with the Remove HUD Background Renderer option being OFF the inventory works fine, sorry I'm dumb

**Comment by AnOpenSauceDev** [comment]
I'm assuming everything works fine with Lunar now? If so, you can go close this issue.

**Comment by kispintyi** [comment]
Where can I set the toggle fullbright keybind?

**Comment by kispintyi** [comment]
only the toggle fullbright keybind I want to know and yes, other than that it works fine I think :D

**Comment by kispintyi** [comment]
BTW Off Topic question: Is it safe to upload crash logs to github (to the internet) like I did here?

**Comment by AnOpenSauceDev** [comment]
> Where can I set the toggle fullbright keybind?

It's somewhere in controls, look for the Methane header.

> Is it safe to upload crash logs to github (to the internet) like I did here?

Not really, In your case I can't see anything personal, but some logs can contain personal/account login information. I'd recommend using an actual log uploading service.

**Comment by kispintyi** [comment]
There is only toggle Methane:
![image](https://github.com/AnOpenSauceDev/Methane-mod/assets/116653691/4546ebd7-4aff-4000-aeda-dae6a596c898)

**Comment by kispintyi** [comment]
> Not really, In your case I can't see anything personal, but some logs can contain personal/account login information. I'd recommend using an actual log uploading service.

https://mclo.gs/ ?

**Comment by AnOpenSauceDev** [comment]
That's the keybind, pressing it while everything is bright turns off Methane, pressing it when everything is normal turns it back on. Doing it while everything is "normal" uses more RAM than not having any light data loaded, but lets you pause and unpause lighting updates.

**Comment by AnOpenSauceDev** [comment]
> https://mclo.gs/ ?

Most launchers use that, and it tries to erase anything personal it finds.

**Comment by kispintyi** [comment]
oh, so I can't actually turn fullbright off but Methane? Okay then, thank you for your help, you were the first to fix Lunar compatibility out of the mods I listed here: https://modrinth.com/modpack/mcc-island-optimised
![image](https://github.com/AnOpenSauceDev/Methane-mod/assets/116653691/04b5c032-9678-455d-a29f-de73ade289ef)

Thank you!

**Comment by kispintyi** [comment]
> Most launchers use that, and it tries to erase anything personal it finds.

Okay, thank you! 👍

**Comment by AnOpenSauceDev** [comment]
> oh, so I can't actually turn fullbright off but Methane?

Methane does still have a handful of smaller optimizations (as you can tell, the particle one is broken by lunar), but the most RAM and CPU savings come from not having a lightmap, and/or not having to update it if you've togged before.

So, methane still does things without the "fullbright", but it's less effective. Dynamic Shading is a pretty good way to sync brightness with time if it's too jarring for you.
