### ISSUE TITLE
Particles become black when re-enabling Methane

### ISSUE THREAD

**Issue by Tetro48** [AnOpenSauceDev/Methane-mod#102]
# 🔥 Something broke!

## Description of what happened
Usually, the particles look fine, but when I toggled it off then on, the particles looked as if they're in a dark place.

## Mods used
Sodium

## Methane Version
Methane 3.8.1 @ 1.20.6
## possible ways to replicate this bug
Toggle it off then on, and then look at particles.

**Comment by AnOpenSauceDev** [comment]
Cannot replicate in just vanilla + Methane. I'll check for Sodium.

**Comment by AnOpenSauceDev** [comment]
I forgot to post the follow-up to this issue, but I couldn't replicate this in any way. Closing due to irreplicability.
