### ISSUE TITLE
[Issue] Same as #47 - No mob spawn in singleplayer

### ISSUE THREAD

**Issue by CDXX710** [AnOpenSauceDev/Methane-mod#108]
## Description of what happened:

No mob spawns on light level 0 in singleplayer as described in issue #47 , neither from spawners. Instant fix from toggling Methane off. Using legacy engine or not does not seems effective.

## Mods used:

( I doubt it matters )

- 	- afkplus 1.5.0
- 	- ambientenvironment 17.0.0.5
- 	- ambientsounds 6.0.3
- 	- antientitygrief 1.0.2
- 	- architectury 13.0.3
- 	- badoptimizations 2.1.4
- 	- balm-fabric 21.0.11
- 	- betterbeds 1.4.0
- 	- bettergrass 1.0.17+1.21
- 	- betterhurtcam 1.9.1+mc1.21
- 	- carpet 1.4.147+v240613
- 	- carpet-ams-addition 2.44.6
- 	- carpet-tis-addition 1.60.1
- 	- chat_heads 0.12.7
- 	- chunky 1.4.16
- 	- cicada 0.8.1+1.21-and-above
- 	- clientsort 0.4.0
- 	- cloth-config 15.0.127
- 	- collective 7.70
- 	- collisionfix 1.0.1
- 	- continuity 3.0.0-beta.5+1.21
- 	- creativecore 2.11.34
- 	- cullleaves 3.4.0
- 	- deepslateinstamine 2.5_release_mc1.21
- 	- disableportalchecks 1.0.0
- 	- disablerocketplaced 1.0.0
- 	- distanthorizons 2.1.2-a
- 	- entity_model_features 2.1.3
- 	- entity_texture_features 6.1.3
- 	- entityculling 1.6.6
- 	- f3sconfirm 1.0.2
- 	- fabric-api 0.100.4+1.21
- 	- fabricloader 0.15.11
- 	- fadeless 1.0.1
- 	- fallingleaves 1.16.0
- 	- fastchest 1.5+1.20.2
- 	- faster-random 4.1.0
- 	- fastipping 1.0.3
- 	- fastitems 1.0.0-1.21
- 	- ferritecore 7.0.0
- 	- feytweaks 1.21-1.2.8
- 	- fixedanvilrepaircost 3.3
- 	- forcecloseworldloadingscreen 2.2.2
- 	- fpsreducer 1.21-2.9
- 	- huskdropsand 1.21-9-fabric
- 	- immediatelyfast 1.2.18+1.21
- 	- indium 1.0.34+mc1.21
- 	- inventoryessentials 21.0.2
- 	- iris 1.7.3+mc1.21
- 	- java 21
- 	- krypton 0.2.8
- 	- lithium 0.12.7
- 	- lithostitched 1.2.0
- 	- methane 3.8.2
- 	- minecraft 1.21
- 	- modelfix 1.21-1.6
- 	- modmenu 11.0.1
- 	- morechathistory 1.3.1
- 	- narrus_yeetus 1.1.0
- 	- ok_zoomer 9.0.2
- 	- overhauledstructures 0.1.4-Fabric-1.21
- 	- placeholder-api 2.4.0+1.21
- 	- reeses-sodium-options 1.7.2+mc1.21
- 	- roguelike 2.0.8-1.21-fabric
- 	- servercore 1.5.4+1.21
- 	- showmeyourskin 1.11.1+1.21
- 	- shulkerboxtooltip 5.0.3+1.21
- 	- sodium 0.5.11+mc1.21
- 	- sodium-extra 0.5.7+mc1.21
- 	- soundcontroller 1.1.3
- 	- stutterfix mc1.21-0.2.2
- 	- tectonic 2.4.0
- 	- ukulib 1.3.0+1.21
- 	- videotape 1.0.0
- 	- world-host 0.4.13+1.21-fabric
- 	- yeetusexperimentus 87.0.0
- 	- yet_another_config_lib_v3 3.5.0+1.21-fabric

## Methane Version:

Methane - 3.8.2 (MC1.21.0) - Modrinth

## Possible ways to replicate this bug:

Open a singleplayer world and watch by night in a plain biome ?

**Comment by AnOpenSauceDev** [comment]
The ability to make mobs spawn anyways was removed a very long time ago, because with Methane either no mobs can spawn, or mobs can spawn literally anywhere regardless of light level. This made me decide to just make everything work at light level 15, and to colour the world darker to hide the fact.

**Comment by yum13241** [comment]
So mobs won't spawn at night?

**Comment by AnOpenSauceDev** [comment]
Yes, Methane isn't like other fullbright mods. It completely obliterates the lighting engine, which kinda leaves this only useful for multiplayer/redstone.

**Comment by CDXX710** [comment]
Is there no possible workaround?

If every block were set on brightness 0 and then change the spawn algorithm to avoid a 15blocks radius from any light source,
Would rhe calculation still be too expensive? At least for singleplayer or really small servers ?

I never got the opportunity really to get into Minecraft modding but i'd be interested to help or anything if I can, especially for this mod that I much cherish because the performances are like no other...

**Comment by AnOpenSauceDev** [comment]
The issue is that you're kinda just iterating through tonnes of blocks (the engine has no idea of what is and isn't a light source unless you go check a block's properties) to check this stuff in a way that's already similar to how minecraft's lighting works, albeit a bit faster.

At that point, you're essentially making a really lightweight lighting engine. I might look into something like this if that's what the community wants, but I've kinda been working on other things (hence why most of my projects are being updated "when I want to").

**Comment by CDXX710** [comment]
I mean I already had in mind to make a fork of Methane (for personal use) and find a workaround that would suit me. But if you agree, I'd be glad to share my work with you, and if any solid progress is done on this side the project could get published one day. But as I also said earlier this would be a first for me so don't expect anything from this x)

**Comment by AnOpenSauceDev** [comment]
Nothing's stopping you from forking Methane, feel free to do whatever.

**Comment by yum13241** [comment]
What if you make Methane disable itself at night? Surely you can detect it's night without a light engine? Mob farms would only work at night though.

**Comment by AnOpenSauceDev** [comment]
I mean it does know when it's night, as Methane re-colours chunks to be darker at night, but it's hard to tell what is fine for mobs and what isn't. What's the difference between your wide, 3-block tall house and a mob farm when we don't have lighting data?
