### ISSUE TITLE
Blocks do not highlight

### ISSUE THREAD

**Issue by bnikoo** [AnOpenSauceDev/Methane-mod#11]
With methane https://modrinth.com/mod/methane/version/1.4.5 alone and with other mods - As pictured, breakable block even in survival mode don't have the grey outline you expect from targeting a block. Breaking blocks and placing work as normal but without the target indicator. 
![2023-01-12_20 18 02](https://user-images.githubusercontent.com/115047706/212257002-e44dcd96-be92-4f4f-9284-28006bd3b4b3.png)

**Comment by AnOpenSauceDev** [comment]
I believe that this was a change I left over from an older build. Should be an easy fix

**Comment by AnOpenSauceDev** [comment]
issue fixed as of https://github.com/AnOpenSauceDev/Methane-mod/commit/a27378a06a7344bcd6d60c370620aad68acd8ab3
