### ISSUE TITLE
[Enhancement/Suggestion] more destructive settings

### ISSUE THREAD

**Issue by justaguywhowantsminecraftmods** [AnOpenSauceDev/Methane-mod#110]
destructive settings like destroy foliage so grass and flowers wouldnt render or like destroy skulls.

Not sure that this would make to much of a difference for fps or anything but I think it makes the game cleaner

**Comment by AnOpenSauceDev** [comment]
For things like skulls, that stuff has collision, so I probably wouldn't touch that.

Foliage can easily be removed via a texture pack, so there isn't too much of a purpose, as you should still be able to highlight and break grass if you can't see it. And yeah, there probably won't be much of a performance gain from doing this.
