### ISSUE TITLE
replay mod compability

### ISSUE THREAD

**Issue by Cyclopropinon** [AnOpenSauceDev/Methane-mod#13]
hi, i went through your [compability list](https://github.com/AnOpenSauceDev/Methane-mod/blob/master/Compatability.md) and i couldnt find [replay mod](https://modrinth.com/mod/replaymod). would be kind if you add it. tyvm

**Comment by AnOpenSauceDev** [comment]
ill go add it now, and probably test it tomorrow

**Comment by AnOpenSauceDev** [comment]
@Cyclopropinon seems to be working fine.

**Comment by Cyclopropinon** [comment]
thanks
