### ISSUE TITLE
mode-switching requires a rejoin

### ISSUE THREAD

**Issue by AnOpenSauceDev** [AnOpenSauceDev/Methane-mod#15]
Currently in Methane-Next, _**you have to re-join your world/server for the changes to properly take effect.**_ Ideally you could just press the toggle key and continue, but nothing actually happens until you leave your old render distance, and even then a lot of things break.

**Comment by slushie0** [comment]
I guess a solution would be to reload all chunks, right? It wouldn't be optimal but it would be better than relogging.

**Comment by AnOpenSauceDev** [comment]
> I guess a solution would be to reload all chunks, right? It wouldn't be optimal but it would be better than relogging.

That's what I thought when I was messing around with it, but the moment you initialize the lighting system everything breaks.

**Comment by AnOpenSauceDev** [comment]
moving this to a project
