### ISSUE TITLE
Are there plans for an 1.19.2 version?

### ISSUE THREAD

**Issue by Reffler** [AnOpenSauceDev/Methane-mod#2]
I really like your mod btw! Good job!

Another small question: Do you think this brings more performance than Starlight (considering this one fully removes lighting)?

**Comment by AnOpenSauceDev** [comment]
@Reffler i'll see if i can backport this mod- and i do _think_ that there is a performance lift when using this mod over starlight. You can use starlight on the server so i would recommend doing that

**Comment by AnOpenSauceDev** [comment]
@Reffler there is now a [1.19.2 build](https://modrinth.com/mod/methane/version/1.2-backport). Looks like I have fixed this issue, so i'm going to close it.
