### ISSUE TITLE
Fog still exists with Sodium 0.4.9 (Methane 1.6.2)

### ISSUE THREAD

**Issue by Critsweep** [AnOpenSauceDev/Methane-mod#22]
Fog still appear when using Sodium
Logs:
https://mclo.gs/mVfnMHY

Screenshots:
![Screenshot (5)](https://user-images.githubusercontent.com/107408962/219011280-d64e18b8-f2b6-4a05-b079-98377c655d68.png)
![2023-02-15_03 07 11](https://user-images.githubusercontent.com/107408962/219011340-08355c1b-f8e3-4194-9cc5-67332747e358.png)

**Comment by AnOpenSauceDev** [comment]
have you disabled it in config? 1.6.2+ now requires you to disable fog manually

**Comment by AnOpenSauceDev** [comment]
@Critsweep it's working fine for me with all fog options disabled, if Methane is toggled/disabled, you'll have to enable _"Persist Fog"_

**Comment by Critsweep** [comment]
Oh, so you need to disable it in the config first, okay get it, I will do that once I got back and inform you later. Thanks in advance!

(I think it would be better if the fog was automatically disabled, so you dont have to configure it)

**Comment by Critsweep** [comment]
Okay it does work, but I think that the configuration resets everytime I relaunch minecraft, kinda annoying to deal with but I think it's fine

**Comment by AnOpenSauceDev** [comment]
#23 will probably fix this
