### ISSUE TITLE
Text not turning white with VanillaTweaks dark gui

### ISSUE THREAD

**Issue by Teslicek** [AnOpenSauceDev/Methane-mod#24]
Self-explanatory. The text in GUI should be white, but with Methane, its black.

**Comment by AnOpenSauceDev** [comment]
That's odd, as methane shouldn't be causing that.

**Comment by AnOpenSauceDev** [comment]
if you have any logs, that would help me debug this.

**Comment by AnOpenSauceDev** [comment]
@Teslicek on closer inspection, it looks like VanillaTweaks has a new shader that overlays color onto the text
[rendertype_text.fsh.txt](https://github.com/AnOpenSauceDev/Methane-mod/files/10787988/rendertype_text.fsh.txt), and that some mod (probably sodium or iris) is overriding this shader, causing it to default to the vanilla dark grey.

**Comment by Teslicek** [comment]
Hi, I dont exactly know what is causing this visual glitch, but with my mods, it only happens when I replace Starlight with Methane.

**Comment by AnOpenSauceDev** [comment]
looking further at this, it seems that **VanillaTweaks is actually generating fog** over the text via the new 1.17+ shader system. This is really weird and I'll have to look into it.

**Comment by AnOpenSauceDev** [comment]
this issue really applies to the VT pack, and it's probably up to them to fix it (no idea if they will)

**Comment by AnOpenSauceDev** [comment]
the "fix" for this would be very annoying, so hopefully VT ends up releasing the fix.
