### ISSUE TITLE
Error message. (might be me not sure)

### ISSUE THREAD

**Issue by SpeedEpic** [AnOpenSauceDev/Methane-mod#26]
I am getting this error message. Not sure if it is something I am doing wrong though.
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'methane'!
Is there a discord for this project at all?

**Comment by AnOpenSauceDev** [comment]
try adding [cloth config](https://modrinth.com/mod/cloth-config) and [mod menu](https://modrinth.com/mod/modmenu), something is missing, causing minecraft to crash.

**Comment by SpeedEpic** [comment]
I also tried launching without any other mods, using only Methane 1.6.3
It still would not open. So I know that this issue is not an incompatability issue.

**Comment by SpeedEpic** [comment]
I will try with just methane, cloth, and mod menue.

**Comment by AnOpenSauceDev** [comment]
Methane also uses the fabric api.

**Comment by SpeedEpic** [comment]
ok, I use that normally and will include it in this test.

**Comment by SpeedEpic** [comment]
[crash-2023-02-27_11.46.58-client.txt](https://github.com/AnOpenSauceDev/Methane-mod/files/10843179/crash-2023-02-27_11.46.58-client.txt)

**Comment by AnOpenSauceDev** [comment]
What version of cloth config are you using? It seems to be crashing again.

**Comment by SpeedEpic** [comment]
![Screenshot (148)](https://user-images.githubusercontent.com/96953005/221660281-143a3455-fb55-42f2-97df-25be4b573d6d.png)
![Screenshot (147)](https://user-images.githubusercontent.com/96953005/221660284-f041ee42-6640-4f90-b7c5-7eef619b99be.png)
These are my PC specs with 16 gigs of ram(8 for minecraft)

**Comment by AnOpenSauceDev** [comment]
that shouldn't be a problem

**Comment by SpeedEpic** [comment]
Good question about cloth config, Just clued in to the fact that it is the forge version I am using.  I thought it was forge and fabric in the same jar. I will assume that is the issue but will let you know if it continues.

**Comment by SpeedEpic** [comment]
It worked! thanks and sorry it was such a stupid problum. XD

**Comment by AnOpenSauceDev** [comment]
no problem!
