### ISSUE TITLE
[Issue] The world will be dark when using Complementary Shaders.

### ISSUE THREAD

**Issue by WForst-Breeze** [AnOpenSauceDev/Methane-mod#29]
# 🔥 Something broke!

## Description of what happened
The world will be dark when using Complementary Shaders.
![image](https://user-images.githubusercontent.com/110760354/222942540-2e976290-f7af-4fac-ab78-c5dde6bb1487.png)

## Mods used
sodium+iris

## Methane Version
Methane - 1.6.3: 1.19.3

## possible ways to replicate this bug
Launch a modpack with Sodium, Iris and Methane mod, then use the Complementary Shaders.

**Comment by AnOpenSauceDev** [comment]
I believe this is the same issue as #12. There isn't really anything that can be done due to what methane does, apart from toggling the mod off.

**Comment by AnOpenSauceDev** [comment]
some shaders use their own lightmaps (methane removes the vanilla ones), and don't have any issues with this.

**Comment by WForst-Breeze** [comment]
Alright, I get it. Thank you for your reply~ :D
