### ISSUE TITLE
this mod breaks my pc

### ISSUE THREAD

**Issue by Ev3rgarden** [AnOpenSauceDev/Methane-mod#3]
i dont know how you wrote it but holy shit i cant even create a crash file for you because my ENTIRE pc hardcrash when trying to start with a fresh install of fabric 1.19.3 with only ur mod

hardware (new and all drives up todate)

12600k
rx 6600
500ssd
16gb ram 3200rz
win11 october update

**Comment by AnOpenSauceDev** [comment]
weird... i can't see how this would cause a hard crash though, as it doesn't do anything dangerous that could make that happen in the first place.

**Comment by AnOpenSauceDev** [comment]
unless you have an event viewer log, i don't know how i can help or fix this. Even on windows i can't force this kind of crash.

**Comment by AnOpenSauceDev** [comment]
Nothing is really happening here, so I'm going to close.

**Comment by TheoCGaming** [comment]
Does this happen with other mods?
How much RAM do you have?
Have you checked your computer for malware? I would recommend using Windows Defender or Malwarebytes.
What graphics card are you using? If you aren't using a graphics card, what processor are you using?
