### ISSUE TITLE
[read first] On the topic of shaders

### ISSUE THREAD

**Issue by AnOpenSauceDev** [AnOpenSauceDev/Methane-mod#30]
# Methane and shaders
This is a pretty important thing - **Most shaders don't work with methane!** Unlike Full-Bright mods, Methane _does not_ keep lightmaps, meaning that any shader trying to grab that data will most likely make the terrain infinitely dark.

Some shaders do work (usually at high settings or with advanced lighting features turned on), mainly those that have their own lightmapper instead of the stock vanilla one, but those can still have some issues with Methane.

# 🤔 so why not keep lightmaps?
~~The issue is that lightmaps and their slow updates are one of the bigger sources of lag in Minecraft. Some mods try to optimize this, like Phosphor and Starlight, but I decided on removing them outright. After all, Methane was initially made for a crappy Pentium laptop.~~ **As of 3.0.0, lightmaps will be frozen and stored with Methane ON, solving most of the performance side of things.**

## What about raytracing shaders?
all the path-traced shaders I've tried _so far_ **work perfectly**, so you should be fine there.

(this will be updated if any issue adds to this)

**Comment by silverace71** [comment]
could you list some path traced shaders by any chance?

**Comment by AnOpenSauceDev** [comment]
@silverace71 
> could you list some path traced shaders by any chance?

Rethinking Voxels, SEUS PTGI (E12), i think HRR works too. Sodium breaks most of the RT shaders it seems

**Comment by Dreig-Michihi** [comment]
Shrimple shaders work quite well!

**Comment by AnOpenSauceDev** [comment]
Complementary Reimagined Ultra (might have a setting to do with real-time lighting somewhere) completely ignores MC's lightmapper, so it works perfectly with Methane.

**Comment by AnOpenSauceDev** [comment]
more shaders should be working now with Methane, as it now caches light data

**Comment by AnOpenSauceDev** [comment]
As of 3.0.0, this issue is generally outdated now. Way more shaders work correctly (Complimentary Reimagined, Unbound, etc.), and sometimes toggling twice is all that's needed to make these work in multiplayer.
