### ISSUE TITLE
[Enhancement/Suggestion] Brightness depend on daytime

### ISSUE THREAD

**Issue by Dreig-Michihi** [AnOpenSauceDev/Methane-mod#33]
May be at night Methane could show blocks not that bright? So it'd look better with somehow supported shaders

**Comment by AnOpenSauceDev** [comment]
this might help out a bit, but I think most shaders still wont work too well with it. Probably will make night-time less jarring ingame though

**Comment by Cyclopropinon** [comment]
if u add it, pls make it toggleable in the settings

**Comment by AnOpenSauceDev** [comment]
> if u add it, pls make it toggleable in the settings

any visual change should be a config option imo

**Comment by AnOpenSauceDev** [comment]
I've kind of done a weird version of this with some of the under-the-hood changes to Methane with 3.0.0
Not closing, as it relies on the user toggling to update the lighting (not done automatically).

**Comment by AnOpenSauceDev** [comment]
I've worked a bit on this today, and have almost gotten the feature fully working! The only issue is that the light change only adapts after a block update in that chunk occurs. I'll see if I can fix that tomorrow.

**Comment by AnOpenSauceDev** [comment]
Fixed in 3.4.0!
