### ISSUE TITLE
[Issue] 1.20 is broken

### ISSUE THREAD

**Issue by Cyclopropinon** [AnOpenSauceDev/Methane-mod#34]
## Description of what happened
methane worked fine till 23w14a (by editing fabric.mod.json), but it broke for 23w16a

## Mods used
methane 1.7
cloth config 10.0.96
fabric api for 23w16a

## possible ways to replicate this bug
join a server; then it crashes
maybe u already want to update methane to 1.20
might be an issue with MatrixStack screen. not sure tho
it seems to be a fundamental change, because all 1.19.4 mods that worked fine for 23w14a broke for 23w16a (game crashes while launching/joining server)

## crashreport
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-04-21 01:03:34
Description: Unexpected error

java.lang.AbstractMethodError: Receiver class me.wolfie.methane.client.HudRenderListener does not define or inherit an implementation of the resolved method 'abstract void onHudRender(net.minecraft.class_332, float)' of interface net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$zhd000$fabric-rendering-v1$render(class_329.java:1393)
	at net.minecraft.class_329.method_1753(class_329.java:371)
	at net.minecraft.class_757.method_3192(class_757.java:918)
	at net.minecraft.class_310.method_1523(class_310.java:1203)
	at net.minecraft.class_310.method_1514(class_310.java:786)
	at net.minecraft.client.main.Main.main(Main.java:240)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$zhd000$fabric-rendering-v1$render(class_329.java:1393)
	at net.minecraft.class_329.method_1753(class_329.java:371)

-- Affected level --
Details:
	All players: 1 total; [class_746['Cyclopropinon'/2857, l='ClientLevel', x=192.87, y=133.00, z=-246.02]]
	Chunk stats: 729, 248
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,73,0), Section: (at 0,9,0 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 119784655 game time, 129434541 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2394)
	at net.minecraft.class_310.method_1514(class_310.java:810)
	at net.minecraft.client.main.Main.main(Main.java:240)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 23w16a
	Minecraft Version ID: 23w16a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 359664912 bytes (343 MiB) / 671088640 bytes (640 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz
	Identifier: Intel64 Family 6 Model 37 Stepping 5
	Microarchitecture: Westmere (Client)
	Frequency (GHz): 2.66
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA NVS 3100M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x0a6c
	Graphics card #0 versionInfo: DriverVersion=21.21.13.4201
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 15219.67
	Virtual memory used (MB): 10379.44
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 2109.98
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.78.1+1.20
			fabric-api-base: Fabric API Base 0.4.23+9ff28bce67
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.26+eff2638667
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c6467
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d167
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f67467
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b867
			fabric-command-api-v1: Fabric Command API (v1) 1.2.26+f71b366f67
			fabric-command-api-v2: Fabric Command API (v2) 2.2.5+df5b2a9d67
			fabric-commands-v0: Fabric Commands (v0) 0.2.43+df3654b367
			fabric-containers-v0: Fabric Containers (v0) 0.1.55+df3654b367
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.0+eff2638667
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daa67
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe67
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.0.0+eff2638667
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8fa67
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.14+eff2638667
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bf67
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.53+df3654b367
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.33+eff2638667
			fabric-item-api-v1: Fabric Item API (v1) 2.1.18+eff2638667
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.0+eff2638667
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957e67
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b367
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca167
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.29+eff2638667
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.33+9e7660c667
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be4067
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.39+eff2638667
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3b67
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.2+eff2638667
			fabric-networking-v0: Fabric Networking (v0) 0.3.42+df3654b367
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 10.0.0+eff2638667
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495b67
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.9+a1ccd7bf67
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.5+eff2638667
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.5+eff2638667
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.1+81e8c57667
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.38+df3654b367
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3e67
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495b67
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.41+df3654b367
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.0+eff2638667
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4ee67
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+03ffe37867
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.0+eff2638667
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.21+eff2638667
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821167
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.1+eff2638667
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.0.1+848ffaab67
		fabricloader: Fabric Loader 0.14.19
		java: OpenJDK 64-Bit Server VM 17
		methane: Methane 1.7
		minecraft: Minecraft 1.20-alpha.23.16.a
	Launched Version: fabric-loader-0.14.19-23w16a
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVS 3100M/PCIe/SSE2 GL version 3.2.0, NVIDIA Corporation
	Window size: 1440x837
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 4x Intel(R) Core(TM) i5 CPU M 560 @ 2.67GHz

**Comment by AnOpenSauceDev** [comment]
> umm i removed it. how do i generate the jar file? (https://github.com/Cyclopropinon/Methane-mod-1.20-snapshot-compat/tree/no_hud_listener)

Can't you compile it with your Java IDE?
Copy over the github actions to do it

**Comment by AnOpenSauceDev** [comment]
> what github actions?

it's the CI thing that github uses in order to automatically build,[ it can be found here](https://github.com/AnOpenSauceDev/Methane-mod/actions)

**Comment by Cyclopropinon** [comment]
ok
now how do i run it?

**Comment by AnOpenSauceDev** [comment]
> ok now how do i run it? it says "0 workflow runs" and it nowhere says "run workflow"

that's unusual... Try editing a comment line or something to force it i'd say

**Comment by Cyclopropinon** [comment]
idk how
![grafik](https://user-images.githubusercontent.com/119750500/233588970-64f65358-a4bd-482f-a2b5-e9ea36850195.png)

**Comment by AnOpenSauceDev** [comment]
try making a new one

**Comment by Cyclopropinon** [comment]
new what

**Comment by AnOpenSauceDev** [comment]
> try making a new one, and paste mine in:
> 
> ```yaml
> # This workflow uses actions that are not certified by GitHub.
> # They are provided by a third-party and are governed by
> # separate terms of service, privacy policy, and support
> # documentation.
> # This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
> # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
> 
> name: Java CI with Gradle
> 
> on:
>   push:
>     branches: [ "master" ]
>   pull_request:
>     branches: [ "master" ]
> 
> permissions:
>   contents: read
> 
> jobs:
>   build:
> 
>     runs-on: ubuntu-latest
> 
>     steps:
>     - uses: actions/checkout@v3
>     - name: Set up JDK ☕
>       uses: actions/setup-java@v3
>       with:
>         java-version: '17'
>         distribution: 'temurin'
>     - name: chmod the script so actions wont die 🙃
>       run: chmod +x gradlew
>     - name: Build with Gradle 🔧
>       uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
>       with:
>         arguments: build #pretty crazy, but you CAN run a server via github actions!
>     - name: Publish artifact JARs
>       uses: actions/upload-artifact@v3
>       with:
>         name: build artifacts
>         path: build/libs/*
> ```

you might need to change the name

**Comment by AnOpenSauceDev** [comment]
@Cyclopropinon 
sorry, a new workflow, with a changed name variable

**Comment by Cyclopropinon** [comment]
hm now there are 2 running
how do i specify the branch?

**Comment by AnOpenSauceDev** [comment]
> hm now there are 2 running how do i specify the branch?

change `master` to `no_hud_listener`

**Comment by AnOpenSauceDev** [comment]
@Cyclopropinon i see you just ran another workflow, you have to change these:

## before
``` yaml
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
```

## after
```yaml
on:
  push:
    branches: [ "insert_branch_name_here" ]
  pull_request:
    branches: [ "insert_branch_name_here" ]
```

**Comment by AnOpenSauceDev** [comment]
odd, the [action's workflow file shows something else?](https://github.com/Cyclopropinon/Methane-mod-1.20-snapshot-compat/actions/runs/4763151596/workflow)

(also you can add `yaml` after three of the " ` " symbol to add highlighting)

**Comment by AnOpenSauceDev** [comment]
@Cyclopropinon try pushing an empty commit (add a blank comment line)

**Comment by Cyclopropinon** [comment]
> @Cyclopropinon try pushing an empty commit (add a blank comment line)

done
![grafik](https://user-images.githubusercontent.com/119750500/233593384-ba198055-7d21-4f7e-aece-b703e42b9507.png)

**Comment by AnOpenSauceDev** [comment]
@Cyclopropinon actually, this might be a naming issue, change
```yaml
name: Java CI with Gradle
```
to
```yaml
name: Compile Mod
```

**Comment by Cyclopropinon** [comment]
and it was master again
![grafik](https://user-images.githubusercontent.com/119750500/233594257-b6f3927c-a560-4154-b22d-7c4d2f81eade.png)

**Comment by Cyclopropinon** [comment]
i think this is the problem
![grafik](https://user-images.githubusercontent.com/119750500/233594639-f3728bc9-e590-4755-8694-69795eb6d156.png)
how do i change the branch? if i click it i just goto the main branch
right click also doesnt work

**Comment by AnOpenSauceDev** [comment]
cant you use the branch selector? It should be on the fork's page

**Comment by AnOpenSauceDev** [comment]
and if that doesn't work, just bring and push your changes to master

**Comment by Cyclopropinon** [comment]
ok i ran it
wheres the jar file?

**Comment by AnOpenSauceDev** [comment]
> ok i ran it wheres the jar file?

should be the build artifacts

**Comment by Cyclopropinon** [comment]
ok found it.
ill try it out

**Comment by AnOpenSauceDev** [comment]
@Cyclopropinon i assume that you've fixed this?

**Comment by Cyclopropinon** [comment]
yes
i can now run minecraft with it :)
Thanks for all the help!

(btw i created an pull request, u can merge it into your if u want)

**Comment by AnOpenSauceDev** [comment]
23w17a probably is going to break this with its new engine changes, i'll have to see later

**Comment by Cyclopropinon** [comment]
oof
it will be a hard time till 1.20 is finally out

**Comment by AnOpenSauceDev** [comment]
> oof it will be a hard time till 1.20 is finally out i tested it and minecraft is not able to launch

- as expected, the 1.20 snapshots are gradually changing everything, especially on the text and rendering side (especially post-processing).
Methane for 1.20 will probably release not too long after 1.20, unless the lighting engine change is bigger than i expected.

**Comment by AnOpenSauceDev** [comment]
@Cyclopropinon just threw some code together, and I noticed that oddly enough, fabric crashes before Methane does.
There were a few other bugs, that I quickly changed to be "not red", but I have no idea if it works.

TL:DR Either the fabric api hasn't updated yet, or one of the dependencies finally broke.

**Comment by AnOpenSauceDev** [comment]
_Probably_ ready for whenever 1.20 releases I'd say

**Comment by AnOpenSauceDev** [comment]
I'm currently beta-testing a new 1.20 version, so far no crashing

**Comment by AnOpenSauceDev** [comment]
it seems that a new change has broken methane, and its probably to do with lightmaps

**Comment by ItsRedlyXD** [comment]
Hey, can you fix that change?

I'm 2 dumb, sowwy.

**Comment by AnOpenSauceDev** [comment]
The issue has to do with the whole lighting engine being rewritten, which means that most of methane's optimizations might actually not do much, I'm still looking into that.

**Comment by AnOpenSauceDev** [comment]
In all fairness, the new lighting engine is very fast, [so fast in fact, that starlight is now archived](https://modrinth.com/mod/starlight), and I'm more than happy to archive this mod and move on to other projects I get more enjoyment out of.

**Comment by Cyclopropinon** [comment]
Sad to hear it :(
I loved this mod so much

**Comment by AnOpenSauceDev** [comment]
> Sad to hear it :( I loved this mod so much

I'm not saying that the mod is dead _yet_, it's just that there are things that need more optimization over lighting now, and I don't have too much time for it accounting for life, projects, and procrastinating the switch of my java dev environment to Linux.

**Comment by AnOpenSauceDev** [comment]
This thread is getting really long, so I'm leaving this issue as a progress tracker, and making moving all of this to a new discussion

**Comment by AnOpenSauceDev** [comment]
#42

**Comment by AnOpenSauceDev** [comment]
1.20 is working much better now! If you have an issues, please go mention me in the [megathread](https://github.com/AnOpenSauceDev/Methane-mod/discussions/42)
