### ISSUE TITLE
[Issue] Domains in Java package IDs

### ISSUE THREAD

**Issue by wolfie136** [AnOpenSauceDev/Methane-mod#43]
Heya, you’re currently using Java package IDs beginning me.wolfie, which implies the package is developed by someone related to the wolfie.me domain, which it isn’t. Please could you consider changing your package IDs to use a domain you do own? Many thanks :)

**Comment by AnOpenSauceDev** [comment]
Oh yeah! That was to do with a much older pseudonym I used to go as for plugin dev. I'll get to changing it later on.

**Comment by AnOpenSauceDev** [comment]
https://github.com/AnOpenSauceDev/Methane-mod/commit/2c2a713f9fff6ac4738bd4c246e479fc80d2745a should resolve this
