### ISSUE TITLE
Memory crash on start

### ISSUE THREAD

**Issue by variety754** [AnOpenSauceDev/Methane-mod#45]

**Comment by variety754** [comment]
Oh I'm sorry
I provided wrong crash report

**Comment by variety754** [comment]
I'll send a new one in a few minutes

**Comment by AnOpenSauceDev** [comment]
I'm going to assume that this issue is... fixed? Make a new issue/discussion if you do need help.

**Comment by variety754** [comment]
I'm sorry, I was wrong in reporting this issue, this was not your mod bug

**Comment by AnOpenSauceDev** [comment]
all good, no worries!
