### ISSUE TITLE
modrinth version stops hostile mobs from spawning in singleplayer

### ISSUE THREAD

**Issue by Whessit** [AnOpenSauceDev/Methane-mod#47]
# 🔥 Something broke!

## Description of what happened
go into singleplayer with mod and it stops mobs spawning

## Mods used
methane

_it is recommended to use [GitHub Gists](https://gist.github.com/) when uploading large logfiles._

## Methane Version
_e.g. Methane - 1.5: 1.19.2_

**Comment by AnOpenSauceDev** [comment]
set `Default Terrain Brightness` to `0`, a fix will make this the default.

**Comment by AnOpenSauceDev** [comment]
Fully fixed in Methane 2.1

**Comment by Cyclopropinon** [comment]
noice
