### ISSUE TITLE
[Enhancement/Suggestion] Adding a Hotkey to Enable/Disable In-Game

### ISSUE THREAD

**Issue by spxctreofficial** [AnOpenSauceDev/Methane-mod#48]
## 💡 The Idea.

Add the ability to turn on and off the mod in the game, that way players can choose to quickly turn lighting back on for things that require the lighting on-the-fly (like whether a mob would spawn on a block).

## 🤔 How should it be accomplished?
_how you think it would work best_

Either add an option in Cloth Config to enable/disable the mod, or add a new keybind to the Options/Controls/Keybinds page.

## 📝 Anything else.
_related issues, etc._

Not sure if the implementation to removing the lighting used in Methane works in a way that allows lighting to be disabled or enabled on-the-fly.

**Comment by AnOpenSauceDev** [comment]
You can already press `\` in methane to toggle this, and it's configurable. I just haven't mentioned it before.

**Comment by AnOpenSauceDev** [comment]
* it's worth noting, this is pretty bugged on 1.20 unfortunately. (this is one of the reasons i don't really advertise it)

**Comment by Cyclopropinon** [comment]
oh and please make it by default not bound, cuz every time i update, it will rebind, and i will accidentally toggle it off and get weird stuff i dont want

**Comment by AnOpenSauceDev** [comment]
> oh and please make it by default not bound, cuz every time i update, it will rebind, and i will accidentally toggle it off and get weird stuff i dont want

ill see what i can do

**Comment by AnOpenSauceDev** [comment]
> oh and please make it by default not bound, cuz every time i update, it will rebind, and i will accidentally toggle it off and get weird stuff i dont want

The issue is fixed, but it wont be ready until i can fix another bug

**Comment by AnOpenSauceDev** [comment]
@Cyclopropinon fixed in https://github.com/AnOpenSauceDev/Methane-mod/commit/5a7730fa3e3274b0505599873c1014248dbfc63f
