### ISSUE TITLE
[Issue] Only renders 16x16x16 section with Sodium 0.5.1 and "Disable Air Fog" enabled

### ISSUE THREAD

**Issue by 4vyy** [AnOpenSauceDev/Methane-mod#49]
## Description of what happened
Turning on "Disable Air Fog" with Sodium 0.5.1 results in only the 16x16x16 section that the player is in to be rendered.

## Mods used
Cloth Config v11 11.1.106
Fabric API 0.87.0+1.20.1
Methane 2.1
Sodium 0.5.1

## Methane Version
Methane - 2.1: 1.20.1

## possible ways to replicate this bug
Set "disableAirFog" to true in methane.json or in the ModMenu config screen in an instance with Sodium 0.5.1. Make sure "Use Fog Occlusion" is enabled under Sodium's Performance settings (which it is by default).

**Comment by 4vyy** [comment]
From the CaffeineMC Discord server:

" ***Mods which disable fog are causing visual issues in Sodium 0.5.1!***
- A fix for this will be included in Sodium 0.5.2. In the meantime, turn off any option that disables fog, and remove any mod that disables fog." 

I'll go ahead and close this.

**Comment by AnOpenSauceDev** [comment]
I'll pin this issue for anyone else who is having this problem.
