### ISSUE TITLE
Make it compatible with fabric 0.14.11 

### ISSUE THREAD

**Issue by Remko115** [AnOpenSauceDev/Methane-mod#5]
I use feather client, and they haven't updated the fabric loader to 0.14.12, but they still have it at 0.14.11 . It would be nice if you used the 0.14.11 so that people on feather client can also use it.

**Comment by AnOpenSauceDev** [comment]
alright, should be a one-line change

**Comment by AnOpenSauceDev** [comment]
the latest commits now have this change. I might hold on putting it on modrinth for now to resolve some bugs
