### ISSUE TITLE
[Enhancement/Suggestion] 2 QoL Features to Add

### ISSUE THREAD

**Issue by MrRagtime** [AnOpenSauceDev/Methane-mod#52]
### **No. 1**
- Adding [Phosphor Fabric](https://www.curseforge.com/minecraft/mc-mods/phosphor) / [Phosphor Forge](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge) **(If FML Support is an option)** to the [compatibility list](https://github.com/AnOpenSauceDev/Methane-mod/blob/master/Compatability.md)
### **No. 2**
- Backporting to older versions such as 1.16 | **(If not it cool I understand)**
### **No. 3**
- Forge Support meh but would be nice as an option

## Last Thoughts
**Don't even bother with this if it is too stressful.**

**Comment by AnOpenSauceDev** [comment]
1. I thought that Phosphor didn't work with Methane?
2. I probably could, but would have to backport some features and maintain the code.
3. I think half of the FabricMC community would actively try to hunt me down if I ported to forge, and I don't have any maintainers helping out with development. I might opt for an architectury rewrite/forge port if this happens.

**Comment by MrRagtime** [comment]
sorry for the late reply
I thought the [compatibility list](https://github.com/AnOpenSauceDev/Methane-mod/blob/master/Compatability.md) also included mods that weren't compatible mb
And are far are you able to backport? 1.8 to beta 1.7?
And I can understand the Fabric community lol yea its fine I doubt FML support would be needed unless it is for 1.8

**Comment by AnOpenSauceDev** [comment]
> And how far are you able to backport? 1.8 to beta 1.7? 

In theory, I could easily backport to 1.8 and beta 1.7.3 thanks to legacy/cursed fabric, and probably all the way into Classic Minecraft if i wanted to decompile and mod the 2010/11 way.

> I doubt FML support would be needed unless it is for 1.8

1.8 - 1.19 would probably be the best use-case for a port, and in my experience FML is pretty slow with a large amount of mods, so Methane might help there.

**Comment by MrRagtime** [comment]
1 - For backporting for fabric how long will that take?
2 - And for Forge implementation, how long will that be? - As well as to back port

### (I'm in no rush btw im just curious)

**Comment by AnOpenSauceDev** [comment]
> 1 - For backporting for fabric how long will that take? 2 - And for Forge implementation, how long will that be? - As well as to back port
> ### (I'm in no rush btw im just curious)

I'm working on a lot of stuff, and I don't really have all the time in the world to work on features, but a fabric backport would probably be easy, and a basic forge port could probably be done in a day (again, if I had the time).

**Comment by MrRagtime** [comment]
alright let me know when it is done

**Comment by AnOpenSauceDev** [comment]
Methane 2.15 should work fine with [Sinytra Connector](https://modrinth.com/mod/connector) on forge based on my testing, but I can't really guarantee any support past that.

**Comment by AnOpenSauceDev** [comment]
I don't really see anything else that can be done, especially if I want to maintain some of the newer features I plan to integrate into Methane in the near future, so I'm just gonna close this issue...
