### ISSUE TITLE
[Issue] something broke! 1.20.1 Forge Modpack using connector

### ISSUE THREAD

**Issue by rainysux** [AnOpenSauceDev/Methane-mod#63]
# 🔥 Something broke!

##
https://pastebin.com/tXhZtWT6
It used to run before in my modpack

_it is recommended to use [GitHub Gists](https://gist.github.com/) when uploading large logfiles._

## Methane Version
_e.g. Methane - 2.50: 1.20.1 Forge
## possible ways to replicate this bug
I'll try to track down the mods responsible in a later time

**Comment by rainysux** [comment]
the log says promenade though I might add

**Comment by AnOpenSauceDev** [comment]
Looks like an issue with Promenade, Iron Spellbooks, Xareo's World Map and Methane all fighting over something. Try removing Promenade and Iron Spellbooks to see if that conflict fixes itself.

**Comment by rainysux** [comment]
sorry fir the late response, it seems to work when turning off promenade and irons spell books

**Comment by AnOpenSauceDev** [comment]
Problem solved!

**Comment by rainysux** [comment]
but they dont crash when im not using methane

**Comment by AnOpenSauceDev** [comment]
that likely means that they mess with methane's optimized particles, so i can't really do anything there.
