### ISSUE TITLE
Can't configure Fulbright!

### ISSUE THREAD

**Issue by NoahAdrian** [AnOpenSauceDev/Methane-mod#69]
# I can't turn off Fulbright in the configurations for methane

## Methane Version
 Methane - 2.5.0 and 3.0.0

**Comment by AnOpenSauceDev** [comment]
`Start with Methane on?` doesn't work for you?

**Comment by AnOpenSauceDev** [comment]
I experience a bug when starting it as off with Methane in `3.0.0`, but it's definitely OFF.

**Comment by NoahAdrian** [comment]
I just ended up uninstalling methane all together
