### ISSUE TITLE
Enhancement: Ability to toggle mod

### ISSUE THREAD

**Issue by slushie0** [AnOpenSauceDev/Methane-mod#7]
I often use fullbright, but usually I leave it off. If I could install this mod and be able to toggle it with a keybind, I would definitely use it.

**Comment by AnOpenSauceDev** [comment]
Seems sound, only issue being that the checks might degrade performance. Either way, ill test it in a branch.

**Comment by AnOpenSauceDev** [comment]
some (very buggy) groundwork is being done at https://github.com/AnOpenSauceDev/Methane-mod/tree/1.19.3-toggles

**Comment by AnOpenSauceDev** [comment]
> it would be perfect if it could be used with starlight so you toggle methane on and it disables starlight and vice versa. for now i'll use methane for my instance made just for dueling, it's a really good mod for that thank you so much

I agree, but due to how mixins work I don't think this will ever be a feasible route, as then Methane would actually have to package it's own **heavily modified** version of starlight, then somehow make then work together. With enough time I guess this could theoretically be done, but it would be very difficult.

**Comment by Cyclopropinon** [comment]
what if you just make it toggleable in the settings?

**Comment by AnOpenSauceDev** [comment]
that's not the issue, its making sure everything can easily be switched over without crashing. Settings are the easy part.

**Comment by AnOpenSauceDev** [comment]
an incredibly buggy build of the methane-next branch can be found [here.](https://github.com/AnOpenSauceDev/Methane-mod/files/10530270/methane-next.zip) Toggling somewhat works, but now chunks have to be properly discarded.

**Comment by AnOpenSauceDev** [comment]
as of now, Methane-Next now supports this (still with quite a few bugs). I consider the main issue (toggling in-game) to be fixed, and #15 is probably the better place for this issue now.
