### ISSUE TITLE
(3.0.0) World loading is broken in singleplayer [BUG]

### ISSUE THREAD

**Issue by Zorklis** [AnOpenSauceDev/Methane-mod#70]
Singleplayer will not load with Methane 3.0.0 Fabric

![javaw_AOXBwTQcPu](https://github.com/AnOpenSauceDev/Methane-mod/assets/85455465/93ea1ed8-d590-48b7-bab8-d8f8dbac84f7)

Had my mods but no methane before and everything loaded fine. 

Saw that methane 3.0 got released, put that bad boy in and launched minecraft, it loaded, pressed to load into my world and it got stuck for a long time, not sure it's even loading as I'm going to sleep. If more info is needed, let me know

**Comment by AnOpenSauceDev** [comment]
Looks like a mod compat issue, my instance of 3.0.0 is fine. What's your modlist?

**Comment by CIND3R3LLA** [comment]
Do u have a Starlight mod? If yes - you should remove it from your modlist.

**Comment by Zorklis** [comment]
Oops, it was Starlight

**Comment by AnOpenSauceDev** [comment]
Because of the way that both the mods work, they'll both mess up the loading of light data, and the world will never load.
