### ISSUE TITLE
[Crash] something broke on 1.20.2 with Methane 3.0.0!

### ISSUE THREAD

**Issue by TH3N3WN00B** [AnOpenSauceDev/Methane-mod#72]
# 🔥 Something broke!

## Description of what happened
Closing the minecraft window, it crashes (?)

## Mods used

[Log](https://gist.github.com/TH3N3WN00B/515ba724c3123c4ed99ecdebdd7754ee)

## Methane Version
Methane - 3.0.0: 1.20.2

## possible ways to replicate this bug
I have no idea

**Comment by AnOpenSauceDev** [comment]
Assuming that you pressed the "X" to close minecraft, and your world has saved, that isn't really a problem. It's likely due to a method i used to make sure that minecraft would not break world data when you quit.

**Comment by TH3N3WN00B** [comment]
Well, I mostly play on servers and when I leave the server and close the game it crashed so I kinda worried for a moment, hopefully is not something bad

**Comment by AnOpenSauceDev** [comment]
Shouldn't be a problem then. I don't have this issue on my machine.
