### ISSUE TITLE
An option to re-enable toasts

### ISSUE THREAD

**Issue by VidTu** [AnOpenSauceDev/Methane-mod#75]
## 💡 The Idea.
Methane disables toasts without [mentioning it anywhere here](https://modrinth.com/mod/methane).
There should be an option to allow toasts to function back properly, as they're pretty useful for:
- Custom toasts. (Custom mods showing toasts)
- Large advancement data packs with chat notifications disabled. (like [this one](https://modrinth.com/datapack/blazeandcaves-advancements-pack), chat notifications there can be disabled via settings)
- Custom servers removing the text title of advancement via resource packs and using the advancement name as a message content field.
- Custom servers abusing [compliance requirements](https://minecraft.wiki/w/Java_Edition_1.18.2#General) feature to show periodical notifications. (don't know if possible now, but deffo was possible a year ago with server resource packs)

## 🤔 How should it be accomplished?
An option to re-enable the toasts back.

## 📝 Anything else.
If option to re-enable toasts is not desired, then it'd be nice to mention the removal of toasts on the mod's page.
The way I found it right now is `-Dmixin.debug.export=true` resulting in this:
<details>
<summary>Decompiled mixin export (click to open)</summary>
<img src="https://github.com/AnOpenSauceDev/Methane-mod/assets/60929459/aaf00fdb-3141-4c5b-8011-6ba72369e6a9">
</details>

**Comment by AnOpenSauceDev** [comment]
I can totally make toast behavior configurable, but the config stuff is starting to get messy. I'll push this with Methane 3.2.0 (3.1.0 is not on modrinth due to a handful of bugs.).

**Comment by AnOpenSauceDev** [comment]
github just closed this issue because i said "_should_ fix #75" :facepalm:, I'll close once this is on modrinth.

**Comment by AnOpenSauceDev** [comment]
_now_ this issue is fixed.
