### ISSUE TITLE
[Issue] Fire camp smoke appears black with BSL shaders

### ISSUE THREAD

**Issue by percyx68** [AnOpenSauceDev/Methane-mod#79]
Fire camp smoke appears black with BSL shaders. Only seams to have this issue with this specific shader.

The version I used is the 3.3.0

**Comment by AnOpenSauceDev** [comment]
It sounds like BSL is accessing lighting data for campfire particles. Not much i can really do, as methane prevents minecraft from calculating lighting for tonnes of particles every frame. it _should_ be fine with Methane OFF, at the very least.

Sounds like an issue for BSL, I'm afraid.
