### ISSUE TITLE
[Issue] Conflicting with Starlight

### ISSUE THREAD

**Issue by FurnyGo** [AnOpenSauceDev/Methane-mod#82]
## Description of what happened

When you try to enter the singleplayer world, the load does not progress beyond 0, there are no errors in the logs  
![image](https://github.com/AnOpenSauceDev/Methane-mod/assets/68079109/af7122d3-80f5-4a22-a515-ce33f18bfbb1)

## Mods used

cloth config, fabric api, modmenu, methane, starlight

## Methane Version
Methane - 3.3.0: 1.20.2

**Comment by FurnyGo** [comment]
can be fixed via legacy lighting engine, maybe any warning if starlight detected?

**Comment by AnOpenSauceDev** [comment]
Unfortunately I can't write any code right now at this moment (at least, without guessing in the mobile editor), but I plan on doing something about this when I can.

**Comment by collective169** [comment]
> can be fixed via legacy lighting engine, maybe any warning if starlight detected?

Startlight no longer needed 
![chrome_hYyi7JOnUN](https://github.com/AnOpenSauceDev/Methane-mod/assets/139126616/6de2f332-d19c-4c4f-8369-f9e301dea833)

**Comment by AnOpenSauceDev** [comment]
> [Starlight is] no longer needed

Yes, but there still _is_ a small performance boost, which inevitably will make people install Starlight and try to use it with Methane (despite the warnings in the modrinth page). It's better to at the very least warn them of their mod combination.

> there are no errors in the logs

actually, there should be, at the very least at mod initialization, as the Fabric Loader itself should warn you in the logs as soon as it detects starlight running alongside Methane.
