### ISSUE TITLE
[Issue] Everything is light level 15.

### ISSUE THREAD

**Issue by Alleop5** [AnOpenSauceDev/Methane-mod#88]
## Bug
Somehow all lighting is level 15 (sky).
## Description of what happened
I was just playing MC and saw no mobs. Eventually it came down to this mod.

## Mods used
Cloth Config
Fabric API
Methane
Mod Menu

## Methane Version
3.5.0

## Possible ways to replicate this bug
Void Linux
OpenJDK 17.0.10
PrismLauncher
Add Instance 1.20.4 with Fabric as the Mod Loader
Install Methane, dependencies are automatically installed.
Start a new world with cheats and go to spectator. Go in a cave. F3 and check.

I changed 0 settings from default. Immediately pressed single player.

**Comment by Alleop5** [comment]
https://mclo.gs/HLhQcKv

**Comment by AnOpenSauceDev** [comment]
Yeah, this is what Methane does (at least, by default). I realize that Methane is probably the only mod that does something this destructive without warning the user on first install, but in all fairness, it's good practice to research what you are putting on your computer and executing, as some mods (in this case, methane) break some systems of minecraft, and substitute their own.

**Comment by Alleop5** [comment]
So methane is just supposed to make no mobs spawn? I can't really find anything that says it makes 0 mobs spawn. Issue 85 would make it look like mobs are supposed to spawn. I did my research and found nothing. I know methane destroys light maps.

**Comment by AnOpenSauceDev** [comment]
Yes, methane destroys lightmaps, which means it would cause no mobs to spawn. If you use the "Legacy Lighting Engine", mobs should spawn somewhat normally.
