### ISSUE TITLE
[Issue] Methane does not work with worlds

### ISSUE THREAD

**Issue by FastPhase** [AnOpenSauceDev/Methane-mod#89]
# 🔥 Something broke!

## Description of what happened
Every time i generate a world or open a world the loading screen gets stuck at 0% and yes i tested it with and without methane, the problem only occurs when i use methane

## Mods used
![image_2024-03-20_015138528](https://github.com/AnOpenSauceDev/Methane-mod/assets/145282583/5e289c45-5fa0-4768-8811-1a73a1357b3b)

_it is recommended to use [GitHub Gists](https://gist.github.com/) when uploading large logfiles._

## Methane Version
_e.g. Methane - 3.5.0: 1.20.4_
## possible ways to replicate this bug
Use methane with the mods above, and i apologize i cannot test each mod with methane separately not because i am lazy but because i have a very poor laptop that cannot run the game wthout those mods.

**Comment by AnOpenSauceDev** [comment]
This is because you're using Starlight. As seen in #82 and #70, Starlight causes a world freeze when Methane is used. Starlight's optimizations have been merged into minecraft as of 1.20 anyways, so there isn't really a point in using it.
