### ISSUE TITLE
[Issue] Mushrooms can't be placed

### ISSUE THREAD

**Issue by epicgamerjamer** [AnOpenSauceDev/Methane-mod#90]
# 🔥 Something broke!

## Description of what happened
Methane prevents you from placing mushrooms, in vanilla they can only be placed on blocks with low light levels, including sky light.

## Mods used
Fabric API, Cloth Config, Mod Menu, Methane
[Log](https://gist.github.com/epicgamerjamer/849e39881803329b4130f122d744d95a) (probably not relevant)

## Methane Version
Methane - 3.5.0: 1.20.4
## possible ways to replicate this bug
1. Go into a dark room with no skylight
2. Try to place a mushroom
3. Epicly fail

**Comment by AnOpenSauceDev** [comment]
I might just make the client place it anyways, and if the server doesn't like it, the mushroom will get rejected by the server instead.

**Comment by AnOpenSauceDev** [comment]
Just fixed this in 3.6.0, I'm not sure if this is exactly vanilla friendly, but I just made mushrooms propagate/place regardless of light level when using Methane. This _will_ cause mushrooms to spread a bit faster on the surface or in cases where it's in direct light, but that's about it.
