### ISSUE TITLE
Scoreboard Numbers Appear Where They Shouldn't

### ISSUE THREAD

**Issue by LobbyLC** [AnOpenSauceDev/Methane-mod#92]
Some multiplayer servers (such as MCC Island in this case) override the vanilla scoreboard to remove the red numbers running down the right side, but Methane seems to override this again, thus bringing them back.

I'm unsure whether this is an "issue" or "feature request", but having the ability to remove those numbers (or at least, disable whatever causes them to reappear) would be pretty neat.

| With Methane | Without Methane |
|:---:|---|
| ![With Methane](https://github.com/AnOpenSauceDev/Methane-mod/assets/116382138/8ce911d8-db2a-4a9e-ae0d-1c9efbd93e57) | ![Without Methane](https://github.com/AnOpenSauceDev/Methane-mod/assets/116382138/2ef10b64-8903-4029-9b34-702fc3acab20) |

*(Example screenshot taken using Methane 3.6.0 on Minecraft 1.20.4)*

**Comment by AnOpenSauceDev** [comment]
Methane used to mess with HUD code a long, long time ago, but it doesn't anymore. Not quite sure why this happens.

**Comment by AnOpenSauceDev** [comment]
Nothing happens when playing on hypixel, and this only shows up once you accept a resource pack on MCC Island.

**Comment by LobbyLC** [comment]
Huh, that's really odd. Without Methane, the MCC Island scoreboard displays as intended so I would guess something in the resource pack is somehow conflicting with the mod? I'm not all that smart, but if I'm able to figure out why, I'll let you know. 🤔

**Comment by LobbyLC** [comment]
I've done a little further testing, and by using the "Toggle Methane" keybind twice (to disable and re-enable the mod), the numbers on the scoreboard will stay vanished as intended.

They won't appear again until the next time you close and re-open the instance, which makes me believe something to do with Methane being enabled by default is causing this to happen. I'm unsure whether that information helps narrow the possible causes down, but figured it's worth sharing.

**Comment by LobbyLC** [comment]
Returning to this issue to note that I'm no longer able to reproduce this bug - as intended, the numbers do not appear on the scoreboard, even while using the exact Methane version.

How this happened, I still have no idea, but chances are you were right in saying it was something to do with the MCC Island resource pack. Either way, it appears to be fixed now so I'll close this issue. Thanks!
