### ISSUE TITLE
[Crash] [1.20.1] Incompatibility with open-source mod

### ISSUE THREAD

**Issue by Cixon** [AnOpenSauceDev/Methane-mod#93]
# Description of what happened
Client crashes on start-up when loading Iron's Spells 'n Spellbooks

## Mods in question
[Iron's Spells 'n Spellbooks](https://legacy.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[Methane v2.5.0](https://modrinth.com/mod/methane/version/2.5.0)
|
Used Sinytra Connector | Neoforge 47.1.99

## Details

**Latest Log (line 1088)**
[latest.log](https://github.com/AnOpenSauceDev/Methane-mod/files/15134875/latest.log)

**Mixin:** https://github.com/iron431/irons-spells-n-spellbooks/blob/1.20.1/src/main/java/io/redspace/ironsspellbooks/mixin/ParticleMixin.java

## Methane Version
Methane - v2.5.0: 1.20.1

**Comment by AnOpenSauceDev** [comment]
I believe I have actually fixed this,  but you're using a very old version of Methane, that released far before I was even aware of sinytra connector.
