### ISSUE TITLE
Weird fog at edges of screen

### ISSUE THREAD

**Issue by FASTB1mc** [AnOpenSauceDev/Methane-mod#97]
# 🔥 Something broke!

## Description of what happened
There is a weird fog at the edge of the screen when you are able to see the hotbar and when you are not able to see the hotbar (when you press F1) it disappears. It looks like this when you can see the hotbar:
![2024-05-20_23 06 59](https://github.com/AnOpenSauceDev/Methane-mod/assets/161627820/3dd2b982-7e23-4e84-888e-78aa33206870)
And like this when you cannot see the hotbar:
![2024-05-20_23 07 01](https://github.com/AnOpenSauceDev/Methane-mod/assets/161627820/aa6be85c-00e3-4aed-abc5-e7bb7c3e997d)

## Mods used
That is my mods folder without all the extra mods that have no way of causing the issue.
[mods.zip](https://github.com/AnOpenSauceDev/Methane-mod/files/15385386/mods.zip)

## Methane Version
Methane 3.6.0
## possible ways to replicate this bug
Install Methane 3.6.0

**Comment by AnOpenSauceDev** [comment]
That's Minecraft's Vignette deciding to appear, you'll have to use a vignette removal mod for that. (Sodium Extra can do that iirc).
