### ISSUE TITLE
Mobs Spawning in middle of day out in the open

### ISSUE THREAD

**Issue by FASTB1mc** [AnOpenSauceDev/Methane-mod#98]
# 🔥 Something broke!

## Description of what happened
Loaded up Methane 3.6.0 and mobs started spawning out in a plains biome like this:
![2024-05-22_09 09 03](https://github.com/AnOpenSauceDev/Methane-mod/assets/161627820/2c48cef7-f120-41a1-bfeb-5001cc5b41a9)
![2024-05-22_09 09 11](https://github.com/AnOpenSauceDev/Methane-mod/assets/161627820/c4a24af2-e3fa-4dd9-9fa5-088902864745)

## Mods used
Mods are all part of these 3 collections:
https://modrinth.com/collection/JPWKV4bF
https://modrinth.com/collection/L4XsA7KG
https://modrinth.com/collection/ILAkWAB4
## Methane Version
Methane 3.6.0
## possible ways to replicate this bug
- Log into a world with methane 3.6.0

**Comment by AnOpenSauceDev** [comment]
Sorry for the delay, I recall that this happens when saving a world when it's nighttime. There isn't really a good fix for this, and this usually relegates me using Methane myself to hyper-optimization and multiplayer.

**Comment by FASTB1mc** [comment]
Ok, but I did notice that this was not the case in Methane Version 3.5.0 or below. Something in Methane 3.6.0 changed and is now causing the issue.

**Comment by AnOpenSauceDev** [comment]
[This is the error is question](https://github.com/AnOpenSauceDev/Methane-mod/compare/3.5.0...3.6.0#diff-2e410496f5992f00eb390e645383cefab02fc5fab65c74c72ea72e840241e483L49), as previously Methane forced everything as light level 15. I could revert this change, but it will unfortunately break other things.

**Comment by FASTB1mc** [comment]
What will it break?

**Comment by AnOpenSauceDev** [comment]
I decided to just go and fix the issues this would've caused.
